#!/bin/sh
USER=opc
HOST=129.213.110.32
DIR=kgc/   # the directory where your website files should go

hugo && rsync -avz --delete public/ ${USER}@${HOST}:~/${DIR} # this will delete everything on the server that's not in the local public folder 

exit 0
